const students = ['Bryner  Andrew',
  'Mayan Said',
  'Burr  Stephanie',
  'Keaveny Timothy',
  'Crawford  Aron',
  'Baars Chance',
  'Barrous Billy',
  'Henao Felipe',
  'Zhou  Linda',
  'Pierce  Daquan',
  'Zhao  Karen',
  'Liederbach  Timothy',
  'James Genaya',
  'Julier  Adam',
  'Carrasco  Christopher',
  'Jahng Forest',
  'ayala jhedi',
  'Sokoya  Solomon',
  'Stukes  Diane',
  'Gometi  Ufuoma',
  'Dahal Shalom',
  'Xu  Shirley',
  'Coleman Berniris',
  'Del Castillo  Ricardo',
  'Redway  Michele',
  'Anderson Janelle',
  'Torres Jonathan'];

module.exports = students;
